name: Build (and Push) s3s-docker image

on:
  push:
  pull_request:
  release:
  workflow_call:
    inputs:
      caller-unixtime:
        description: "UnixTime of the caller's workflow execution."
        required: true
        type: string
      s3s-repo-cache-key:
        description: "s3s repository cache key."
        required: true
        type: string
      image-push-to-docker-hub:
        description: "Whether to push the build Docker image to Docker Hub or not."
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      s3s-commit-ref:
        description: "A specific git ref of s3s repository to build Docker image."
        required: false
        type: string

jobs:
  s3s-docker_build-push:
    name: Build s3s-docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Modify Dockerfile to build using checked out repository
        run: |
          sed -i -E "
              3,9d; \
              s@^    (mkdir -p /app/s3s-config && \\\)@\\nRUN \1@; \
              10 i COPY\ s3s/\ /app/s3s \
            " Dockerfile
        shell: bash

      - name: Restore s3s repository cache
        id: restore-s3s-repo-cache
        if: ${{ ((inputs && inputs.s3s-repo-cache-key) || '') != '' }}
        uses: actions/cache/restore@v3
        with:
          key: ${{ inputs.s3s-repo-cache-key }}
          path: |
            ${{ github.workspace }}/s3s
          fail-on-cache-miss: true

      - name: Checkout s3s repository
        if: ${{ steps.restore-s3s-repo-cache.conclusion == 'skipped' }}
        uses: actions/checkout@v3
        with:
          repository: frozenpandaman/s3s
          ref: ${{ (inputs && inputs.s3s-commit-ref) || '' }}
          path: ${{ github.workspace }}/s3s

      - name: Extract s3s information (version / commit hash)
        id: s3s-info-extractor
        uses: ./.github/actions/extract-s3s-information
        with:
          s3s-path: ${{ github.workspace }}/s3s

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      - name: Build (and Push) Image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ inputs && inputs.image-push-to-docker-hub || false }}
          platforms: "linux/amd64,linux/386,linux/arm64,linux/arm,linux/arm/v6"
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/s3s-docker:${{ steps.s3s-info-extractor.outputs.version }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/s3s-docker:latest

      - name: Create build version log
        id: create-build-version-log
        if: ${{ inputs && inputs.image-push-to-docker-hub && steps.build-and-push.conclusion == 'success' }}
        run: |
          mkdir -p ~/version
          echo -n '${{ steps.s3s-info-extractor.outputs.version }}' > ~/version/last

          mkdir -p ~/commit-hash
          echo -n '${{ steps.s3s-info-extractor.outputs.commit-hash }}' > ~/commit-hash/last
        shell: bash

      - name: Store build version log
        if: ${{ steps.create-build-version-log.conclusion == 'success' }}
        uses: actions/cache/save@v3
        with:
          path: |
            ~/version
            ~/commit-hash
          key: build-log-${{ github.sha }}-${{ inputs.caller-unixtime }}
